export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const UPDATE_GAME_STATE_FROM_SERVER = 'UPDATE_GAME_STATE_FROM_SERVER'
export const UPDATE_ALL_GAMES_FROM_SERVER = 'UPDATE_ALL_GAMES_FROM_SERVER'

export const PULL_AND_STAGE_TILES = 'PULL_AND_STAGE_TILES'
export const TRANSFER_TILES_TO_FINAL_ROWS = 'TRANSFER_TILES_TO_FINAL_ROWS'
export const REFILL_FACTORIES = 'REFILL_FACTORIES'
