export const PULL_TILES = 'PULL_TILES'
export const STAGE_TILES = 'STAGE_TILES'
export const TRANSFER_TILES_TO_FINAL_ROWS = 'TRANSFER_TILES_TO_FINAL_ROWS'
export const REFILL_FACTORIES = 'REFILL_FACTORIES'
