export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const NEW_GAME_CREATED = 'NEW_GAME_CREATED' 
export const TILE_TRANSFER = 'TILE_TRANSFER'
export const TILE_PULL = 'TILE_PULL'
export const GAME_STATE_RECEIVED = 'GAME_STATE_RECEIVED'
export const GAME_ACTIONS_RECEIVED = 'GAME_ACTION_RECEIVED'

export const UPDATE_ALL_GAMES_FROM_SERVER = 'UPDATE_ALL_GAMES_FROM_SERVER'
export const CONNECTED_TO_GAME = 'CONNECTED_TO_GAME'
export const RECEIVED_AVAILABLE_GAMES_FROM_SERVER = 'RECEIVED_AVAILABLE_GAMES_FROM_SERVER'
